services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/letsencrypt
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=tu-email@ejemplo.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web

  frontend:
    build:
      context: .                   # contexto = raíz del monorepo
      dockerfile: ab-frontend/Dockerfile
    container_name: ab-frontend
    restart: unless-stopped
    ports:
      - "3333:80"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.ab-frontend.rule=Host(`www.alejandrobenitez.com`) || Host(`alejandrobenitez.com`)"
    - "traefik.http.routers.ab-frontend.entrypoints=websecure"
    - "traefik.http.routers.ab-frontend.tls=true"
    - "traefik.http.routers.ab-frontend.tls.certresolver=le"

volumes:
  traefik-certs:
    driver: local
