# Generated by Django 5.2.8 on 2026-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Imagen')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['order'],
            },
        ),
    ]
