# Generated by Django 5.2.8 on 2026-03-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='portfolio/thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
