"""
Django settings for ab_reservas_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Load environment variables
# Support for python-dotenv if installed
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-qi8#t^b388k)+5*iw%76mxa+l_#y*%)+ri^at)q0b^13e^p5**')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '1') == '1'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # APPS DE ESTE REPO

    # OAuth 2.1 — Django es el authorization server del MCP
    'oauth2_provider',

    'app_links',
    'app_fractalia',
    'app_portfolio',
    'app_analytics',
    'app_mcp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'app_analytics.middleware.PageViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ab_reservas_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ab_reservas_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - read from environment
DATABASE_TYPE = os.environ.get('DATABASE', 'sqlite')

if DATABASE_TYPE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'ab_reservas'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    # Default to SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.environ.get('SQLITE_DB_PATH', 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Asuncion'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Estáticos
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # para colectar en prod

# Solo incluir STATICFILES_DIRS si el directorio existe
_static_dir = BASE_DIR / "static"
STATICFILES_DIRS = [_static_dir] if _static_dir.exists() else []

# WhiteNoise: servir archivos estáticos con compresión de larga duración
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ─── OAuth 2.1 (django-oauth-toolkit) ────────────────────────────────────────
# Django actúa como authorization server del servicio MCP. El MCP es el resource
# server: valida los access tokens contra estas mismas tablas.
#
# El cliente (Claude) se registra solo vía DCR contra /o/register/, así que en
# el diálogo del conector alcanza con la URL: los campos de client id y secreto
# quedan vacíos. También se puede crear la Application a mano desde el admin y
# copiar las credenciales, si se prefiere un cliente fijo.
OAUTH2_PROVIDER = {
    'SCOPES': {
        'fractalia:operar': 'Revisar y confirmar reservas de Fractalia',
    },
    'DEFAULT_SCOPES': ['fractalia:operar'],

    # OAuth 2.1: PKCE obligatorio y sin grants implícitos.
    'PKCE_REQUIRED': True,
    'ALLOWED_SCHEMES': ['https'] if not DEBUG else ['https', 'http'],

    # Tokens cortos + refresh: si se filtra uno, la ventana es chica.
    'ACCESS_TOKEN_EXPIRE_SECONDS': 60 * 60 * 8,        # 8 horas
    'REFRESH_TOKEN_EXPIRE_SECONDS': 60 * 60 * 24 * 30,  # 30 días
    'ROTATE_REFRESH_TOKEN': True,

    # Registro dinámico de clientes (RFC 7591). Es lo que permite dejar
    # vacíos los campos OAuth del diálogo de Claude: el cliente se registra
    # solo contra /o/register/.
    #
    # El registro es abierto porque el cliente que se registra todavía no
    # tiene acceso a nada: para operar, una persona tiene que iniciar sesión
    # en Django y aprobar el consentimiento. Lo único que habilita el registro
    # abierto es crear filas de Application.
    'DCR_ENABLED': True,
    'DCR_REGISTRATION_PERMISSION_CLASSES': (
        'oauth2_provider.dcr.AllowAllDCRPermission',
    ),

    # RFC 9700 (Security BCP) — en DOT 3.x vienen apagadas para no romper
    # instalaciones viejas, y pasan a ser el default en 4.0. Las activamos ya:
    # rechazan los grants inseguros de OAuth 2.0 y endurecen el resto.
    'COMPLIANT_BCP_RFC9700_IMPLICIT_GRANT': True,       # sin grant implícito
    'COMPLIANT_BCP_RFC9700_PASSWORD_GRANT': True,       # sin password grant
    'COMPLIANT_BCP_RFC9700_PKCE_METHOD': True,          # S256 únicamente, sin "plain"
    'COMPLIANT_BCP_RFC9700_ACCESS_TOKEN_TRANSPORT': True,  # token solo por header
    'COMPLIANT_BCP_RFC9700_AUTHZ_RESPONSE_ISS': True,   # iss en la respuesta (anti mix-up)
    'COMPLIANT_BCP_RFC9700_TOKEN_STORAGE': True,        # tokens hasheados en base
    # Estas cuatro solo elevan a error los avisos de `manage.py check --deploy`.
    'COMPLIANT_BCP_RFC9700_REFRESH_TOKEN': True,
    'COMPLIANT_BCP_RFC9700_REDIRECT_URI_SCHEME': True,
    'COMPLIANT_BCP_RFC9700_REDIRECT_URI_MATCHING': True,
    'COMPLIANT_BCP_RFC9700_PKCE_REQUIRED': True,

    'REFRESH_TOKEN_REUSE_PROTECTION': True,
    'ALLOWED_REDIRECT_URI_SCHEMES': ['https'] if not DEBUG else ['https', 'http'],
    'ALLOW_URI_WILDCARDS': False,

    'OAUTH2_VALIDATOR_CLASS': 'oauth2_provider.oauth2_validators.OAuth2Validator',
}

# La pantalla de consentimiento de OAuth exige sesión iniciada. Sin esto Django
# usa su default /accounts/login/, que en este proyecto no existe: el flujo del
# conector terminaba en un 404 justo al autorizar. El único login real es el
# del admin.
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'

# URL pública del authorization server. Debe coincidir con el issuer que
# el MCP anuncia en su metadata de resource server.
OAUTH_ISSUER = os.environ.get(
    'OAUTH_ISSUER', 'https://admin.alejandrobenitez.com')


# CSRF — construir desde ALLOWED_HOSTS o env var
if os.environ.get('CSRF_TRUSTED_ORIGINS'):
    # Si está explícitamente definido en env
    _csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS')
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',')]
else:
    # Si no, construir desde ALLOWED_HOSTS con el scheme correcto
    _scheme = 'https' if not DEBUG else 'http'
    CSRF_TRUSTED_ORIGINS = [
        f"{_scheme}://{host}" for host in ALLOWED_HOSTS if host not in ('*', '127.0.0.1', 'localhost')
    ]
    # Para dev, agregar localhost con http
    if DEBUG:
        CSRF_TRUSTED_ORIGINS.extend(['http://localhost:8000', 'http://127.0.0.1:8000'])

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG

# Sesión compartida entre todos los subdominios de alejandrobenitez.com
# Permite que un admin logueado en admin.alejandrobenitez.com
# sea reconocido también en fractalia.alejandrobenitez.com y links.alejandrobenitez.com
SESSION_COOKIE_DOMAIN = None

# PRODUCCIÓN: Traefik como reverse proxy
# Traefik comunica con Django por HTTP internamente pero el cliente usa HTTPS
# Estos headers le dicen a Django que confíe en Traefik sobre el protocolo real
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Traefik maneja HTTP → HTTPS
    USE_X_FORWARDED_HOST = True
    SECURE_TRUSTED_PROXIES = ['*']  # Confiar en la red Docker de Traefik