# Generated by Django 5.2.8 on 2025-11-05 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DISCRETO', 'Discreto - Slot completo'), ('CONTINUO', 'Continuo - Cliente elige horario')], default='DISCRETO', help_text='DISCRETO: cliente reserva el slot completo. CONTINUO: cliente elige horario dentro del rango.', max_length=10)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_minima_minutos', models.PositiveIntegerField(default=60, help_text='Duración mínima en minutos (solo aplica a slots CONTINUOS)', verbose_name='Duración mínima (minutos)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Horarios Disponibles',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Servicios Adicionales',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cedula', models.CharField(help_text='Número de cédula de identidad', max_length=20, verbose_name='Cédula de Identidad')),
                ('ruc', models.CharField(blank=True, help_text='Registro Único del Contribuyente (opcional)', max_length=20, verbose_name='RUC')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE_VERIFICACION', 'Pendiente de Verificación de Email'), ('PENDIENTE_CONFIRMACION', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_VERIFICACION', max_length=30)),
                ('token_verificacion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email_verificado_en', models.DateTimeField(blank=True, null=True)),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Comentarios del cliente')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas del asistente')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('servicios_adicionales', models.ManyToManyField(blank=True, related_name='reservas', to='app_reservas.servicioadicional')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['cedula'], name='app_reserva_cedula_2ddd9f_idx'), models.Index(fields=['ruc'], name='app_reserva_ruc_51a395_idx'), models.Index(fields=['email_cliente'], name='app_reserva_email_c_a240c9_idx'), models.Index(fields=['fecha', 'estado'], name='app_reserva_fecha_ba5501_idx')],
            },
        ),
    ]
