# Generated by Django 5.2.8 on 2026-02-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodisponible',
            name='duracion_minima_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duración mínima en minutos (solo aplica a CONTINUO)', verbose_name='Duración mínima (minutos)'),
        ),
    ]
