# Generated by Django 5.2.8 on 2026-03-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pageview',
            new_name='app_analyti_page_6ab01e_idx',
            old_name='app_analyti_page_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='app_analyti_ip_hash_f9c120_idx',
            old_name='app_analyti_ip_ts_idx',
        ),
    ]
