# Generated by Django 5.2.8 on 2026-07-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='En palabras del encargado, no en términos técnicos.', verbose_name='Qué necesitaba hacer')),
                ('clave', models.CharField(db_index=True, editable=False, max_length=200, verbose_name='Clave de agrupación')),
                ('categoria', models.CharField(choices=[('falta_tool', 'Falta una herramienta'), ('falta_dato', 'Falta un dato que el sistema no guarda'), ('friccion', 'Se puede, pero cuesta más de lo que debería'), ('error', 'Algo no funcionó como se esperaba'), ('otro', 'Otro')], default='falta_tool', max_length=20, verbose_name='Tipo')),
                ('contexto', models.TextField(blank=True, default='', help_text='Qué se estaba haciendo cuando apareció la necesidad.', verbose_name='En qué estaba')),
                ('tool_relacionada', models.CharField(blank=True, default='', help_text='La que se intentó usar, si hubo alguna.', max_length=60, verbose_name='Herramienta usada')),
                ('veces', models.PositiveIntegerField(default=1, verbose_name='Veces que apareció')),
                ('usuario', models.CharField(blank=True, default='', max_length=150, verbose_name='Reportada por')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('en_analisis', 'En análisis'), ('planificada', 'Planificada'), ('implementada', 'Implementada'), ('descartada', 'Descartada')], db_index=True, default='nueva', max_length=20, verbose_name='Estado')),
                ('nota_equipo', models.TextField(blank=True, default='', verbose_name='Nota del equipo')),
                ('primera_vez', models.DateTimeField(auto_now_add=True, verbose_name='Primera vez')),
                ('ultima_vez', models.DateTimeField(auto_now=True, verbose_name='Última vez')),
            ],
            options={
                'verbose_name': 'Necesidad no cubierta',
                'verbose_name_plural': 'Necesidades no cubiertas',
                'ordering': ('-veces', '-ultima_vez'),
            },
        ),
        migrations.CreateModel(
            name='UsoTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(db_index=True, max_length=60, verbose_name='Herramienta')),
                ('usuario', models.CharField(blank=True, default='', max_length=150, verbose_name='Usuario')),
                ('exito', models.BooleanField(default=True, verbose_name='Salió bien')),
                ('detalle_error', models.TextField(blank=True, default='', verbose_name='Error')),
                ('duracion_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (ms)')),
                ('momento', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cuándo')),
            ],
            options={
                'verbose_name': 'Uso de herramienta',
                'verbose_name_plural': 'Uso de herramientas',
                'ordering': ('-momento',),
                'indexes': [models.Index(fields=['tool', 'momento'], name='app_mcp_uso_tool_92aa2e_idx')],
            },
        ),
    ]
