# Generated by Django 5.2.8 on 2026-02-20 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fractalia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reservation_code', models.CharField(max_length=4, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='app_fractalia.resource')),
            ],
            options={
                'verbose_name': 'Reserva pendiente',
                'verbose_name_plural': 'Reservas pendientes',
                'ordering': ('-created_at',),
            },
        ),
    ]
