# Generated by Django 5.2.8 on 2026-02-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fractalia', '0002_pendingbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingbooking',
            name='client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
