# Generated by Django 5.2.8 on 2026-02-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fractalia', '0004_alter_pendingbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
    ]
