# Generated by Django 5.2.8 on 2026-02-21 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fractalia', '0005_alter_pendingbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono del cliente'),
        ),
        migrations.AddField(
            model_name='pendingbooking',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono del cliente'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app_fractalia.resource', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='CONFIRMED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Recibida'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='end_time',
            field=models.TimeField(verbose_name='Hora fin'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='reservation_code',
            field=models.CharField(max_length=4, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='app_fractalia.resource', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='start_time',
            field=models.TimeField(verbose_name='Hora inicio'),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='whatsapp_number',
            field=models.CharField(help_text='Incluir código de país, e.g. 595981123456', max_length=30, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='end_time',
            field=models.TimeField(verbose_name='Hora fin'),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='app_fractalia.resource', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='start_time',
            field=models.TimeField(verbose_name='Hora inicio'),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día'),
        ),
    ]
