# Generated by Django 5.2.8 on 2026-03-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fractalia', '0007_add_fractabox_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('RESPONDED', 'Respondida'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
    ]
