# Generated by Django 5.2.8 on 2026-03-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fractalia', '0008_add_responded_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FractaboxPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('slots_to_block', models.PositiveIntegerField(verbose_name='Slots a bloquear')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paquete Fractabox',
                'verbose_name_plural': 'Paquetes Fractabox',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='fractabox_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app_fractalia.fractaboxpackage', verbose_name='Paquete Fractabox'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('product_type', models.CharField(choices=[('ALQUILER', 'Alquiler de Estudio'), ('FRACTABOX', 'Fractabox'), ('FOTO', 'Sesión Fotográfica')], max_length=20, verbose_name='Tipo')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible al público')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_fractalia.resource', verbose_name='Recurso')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='fractaboxpackage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='app_fractalia.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app_fractalia.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='pendingbooking',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_bookings', to='app_fractalia.product', verbose_name='Producto'),
        ),
    ]
